<?php

namespace ProjetDGI\GRSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModaliteEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModaliteEvaluationRepository extends EntityRepository
{
}
