<?php

namespace ProjetDGI\GRSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEvaluationRepository extends EntityRepository
{
}
