<?php

namespace ProjetDGI\GRPBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ECRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ECRepository extends EntityRepository
{
}
