<?php

namespace ProjetDGI\GRHBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResponsabiliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsabiliteRepository extends EntityRepository
{
}
